# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Childcare Registration, Affordable Child Care Software and App.
email: hello@tingr.org
description: > # this means to ignore newlines until "baseurl:"
  We build innovative products and affordable management child care software for childcare providers. Visit here for childcare registration at tingr.org
keywords: > # this means to ignore newlines until "baseurl:"
  test
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tingr.org" # the base hostname & protocol for your site https://tingr.org
# twitter_username: tingr
# github_username:  tingr
logo: images/@stock/t_logo.png

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose
  # - jekyll-seo-tag
  # - jekyll-sitemap
#
# paginate: 6
# paginate_path: "blog/page:num"

exclude:
  - 'vendor/'
  - 'about.html'
  - 'portfolio.html'
  - 'signup-ori.html'
  - 'contact/'
  - 'blog/'
  - 'bower_components/'

sass:
  style: compressed
