# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: For Childcare Providers. Digital Enrollments & Beyond.
email: hello@tingr.org
description: > # this means to ignore newlines until "baseurl:"
  All-in-One Product for your Child Care.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tingr.org" # the base hostname & protocol for your site https://tingr.org
# twitter_username: tingr
# github_username:  tingr
logo: images/@stock/t_logo.png

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose
  - jekyll-seo-tag
  - jekyll-sitemap
#
# paginate: 6
# paginate_path: "blog/page:num"

exclude:
  - 'vendor/'
  - 'about.html'
  - 'portfolio.html'
  - 'signup-ori.html'
