# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: TINGR. The Childcare Product. Putting Children 1st.
email: support@tingr.org
description: > # this means to ignore newlines until "baseurl:"
  All-in-One Product for your Childcare Center.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://tingr.org" # the base hostname & protocol for your site
twitter_username: tingr
github_username:  tingr

keep_files: [.well-known]

# Build settings
markdown: kramdown


gems:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"

include: [".well-known"]
exclude: [vendor]
